// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxicuufhyuzhrsolwckm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4aWN1dWZoeXV6aHJzb2x3Y2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDQ3MTQsImV4cCI6MjA3MDU4MDcxNH0.67ND9IeqhAm2eA4hPfEj71DzJjoGwaZVyQJNonhhjOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});